{{- if not (eq .Values.enabled "core") }}
{{- $namespace := print $.Values.global.pattern "-" $.Values.clusterGroup.name }}
{{- range .Values.clusterGroup.applications }}
{{- if or (.generators) (.generatorFile) (.useGeneratorValues) (.destinationServer) (.destinationNamespace) }}
{{- if not .disabled }} {{- /* This allows us to null out an Application entry by specifying disabled: true in an override file */}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .name }}
spec:
  {{- if .generators }}
  generators: {{ .generators | toPrettyJson }}
  {{- else }}
  generators:
    - git:
        repoURL: {{ $.Values.global.repoURL }}
        revision: {{ $.Values.global.targetRevision }}
        {{- if .generatorFile }}
        files:
          - path: {{ .generatorFile | quote }}
        {{- end }}
  {{- end }}
  template:
    metadata:
      name: {{ coalesce .namespace $namespace }}
    spec:
      project: {{ .project }}
      {{- if .syncPolicy }}
      syncPolicy: {{ .syncPolicy | toPrettyJson }}
      {{- else }}
      syncPolicy:
        automated: {}
        retry:
          limit: {{ default 20 $.Values.global.options.applicationRetryLimit }}
      {{- end }}
      {{- if .ignoreDifferences }}
      ignoreDifferences: {{ .ignoreDifferences | toPrettyJson | nindent 2 }}
      {{- end }}
      source:
        repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
        targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
        {{- if .chart }}
        chart: {{ .chart }}
        {{- end }}
        {{- if .path }}
        path: {{ .path }}
        {{- end }}
        {{- if .plugin }}
        plugin: {{ .plugin | toPrettyJson }}
        {{- end }}
        {{- if not .kustomize }}
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          {{- include "clustergroup.app.globalvalues.valuefiles" $ | nindent 12 }}
        {{- range $valueFile := $.Values.clusterGroup.sharedValueFiles }}
            - {{ tpl $valueFile $ | quote }}
        {{- end }}
        {{- range $valueFile := .extraValueFiles }}
            - {{ tpl $valueFile $ | quote }}
        {{- end }}
        {{- if .useGeneratorValues }}
          values: |-
            {{ `{{ values }}` }}
        {{- end }}
          parameters:
          {{- include "clustergroup.app.globalvalues.helmparameters" $ | nindent 12 }}
            - name: global.repoURL
              value: {{ $.Values.global.repoURL }}
            - name: global.targetRevision
              value: {{ $.Values.global.targetRevision }}
            - name: global.namespace
              value: {{ $.Values.global.namespace }}
            - name: clusterGroup.name
              value: {{ $.Values.clusterGroup.name }}
        {{- range .extraHubClusterDomainFields }}
            - name: {{ . }}
              value: {{ $.Values.global.hubClusterDomain }}
        {{- end }}
        {{- range .extraLocalClusterDomainFields }}
            - name: {{ . }}
              value: {{ $.Values.global.localClusterDomain }}
        {{- end }}
        {{- range .extraRepoURLFields }}
            - name: {{ . }}
              value: {{ $.Values.global.repoURL }}
        {{- end }}
        {{- range .extraTargetRevisionFields }}
            - name: {{ . }}
              value: {{ $.Values.global.targetRevision }}
        {{- end }}
        {{- range .extraNamespaceFields }}
            - name: {{ . }}
              value: {{ $.Values.global.namespace }}
        {{- end }}
        {{- range .extraPatternNameFields }}
            - name: {{ . }}
              value: {{ $.Values.global.pattern }}
        {{- end }}
        {{- range $k, $v := $.Values.extraParametersNested }}
            - name: {{ $k }}
              value: {{ printf "%s" $v | quote }}
        {{- end }}
        {{- range .overrides }}
            - name: {{ .name  }}
              value: {{ .value | quote  }}
        {{- if .forceString }}
              forceString: true
        {{- end }}
        {{- end }}
        {{- end }}
      destination:
        server: {{ coalesce .destinationServer "https://kubernetes.default.svc" }}
        namespace: {{ coalesce .destinationNamespace .namespace $namespace }}
{{- end }} {{- /* if .disabled */}}
{{- end }}{{- /* if or (.generators) (.generatorFile) (.useGeneratorValues) (.destinationServer) (.destinationNamespace) */}}
{{- end }}{{- /* range  */}}
{{- end }}{{- /* if not core */}}
